# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  Server:
    build:
      context: "/Users/denis/Downloads/Server"
      dockerfile: "Server/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Server.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "server:dev"
    ports: []
    volumes:
    - "/Users/denis/Downloads/Server/Server:/app:rw"
    - "/Users/denis/Downloads/Server:/src:rw"
    - "/Users/denis/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
