version: '3.8'

services:
  Server:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "8888:8888"
    expose:
      - 8888
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=PersonDB;User Id=sa;Password=P@ssw0rd;
    depends_on:
      - db

  db:
    container_name: db
    hostname: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    expose:
      - 1433